### ISSUE TITLE
Modify existing pdf file?

### ISSUE THREAD

**Issue by tylerlong** [ishaq/SimplePDF#1]
Thank you for creating such an awesome library!

Let's say I have a pdf file, it's very long but there is not table of contents.

Is it possible to use SimplePDF to modify the pdf file?

**Comment by ishaq** [comment]
thank you. 

as for your question. sorry, it can't do that. It's just a simple library that lets you create simple pdf documents. I plan to add more features to it but this feature is **too big** to implement and is out of scope.

**Comment by tylerlong** [comment]
It's OK. I did some investigation. Modifying exiting PDF seems very hard. http://stackoverflow.com/questions/1333710/how-to-edit-a-pdf-in-objective-c

**Comment by ishaq** [comment]
yup :-)
