### ISSUE TITLE
Add two images in row with caption - Reopen

### ISSUE THREAD

**Issue by KushThakkar** [ishaq/SimplePDF#16]
1 image 1 image

!image 1 image

Like above in one page 4 images

**Comment by ishaq** [comment]
please elaborate.

**Comment by ishaq** [comment]
@KushThakkar what exactly did you want to report? Please elaborate.

**Comment by KushThakkar** [comment]
![screen shot 2016-04-23 at 2 25 12 pm](https://cloud.githubusercontent.com/assets/17953979/14760364/466ea154-095f-11e6-872c-fc73a6a3b92c.png)
i need four images per page and that is 2*2 like in image

**Comment by ishaq** [comment]
call it like this:

``` swift
pdf.addImages([imagePath1, imagePath2, imagePath3, imagePath4], 
    imageCaptions: ["", "", "", ""], 
    imagesPerRow: 2)
```

It will add 4 images (with empty captions) such that there are two images per row `imagesPerRow` argument.

**Comment by KushThakkar** [comment]
but i need caption also

**Comment by KushThakkar** [comment]
i need caption and description for images

**Comment by ishaq** [comment]
please see ReadMe and the example project for usage.

in the above example you can pass captions via `imageCaptions` argument. For description, you should add multi-column text (`addAttributedStringsToColumns(columnWidths: [CGFloat], strings: [NSAttributedString])`) right after adding the images.

**Comment by zetrixweb** [comment]
Hi i have array of image with caption details how i can set four image per page using for loop.
i am sorry but i am new.
