### ISSUE TITLE
Change body text Font Size

### ISSUE THREAD

**Issue by KushThakkar** [ishaq/SimplePDF#17]

**Comment by ishaq** [comment]
1. subclass `DefaultTextFormatter` and override the `attributedStringForStyle(string: String, style: TextStyle)` function.
2. Pass an instance of this subclass to SimplePDF init method. 

SimplePDF will now use your subclass to format text elements. Basically, something like this:

``` swift
// say your subclass is called MyTextFormatter
let myTextFormatter = MyTextFormatter()
let pdf = SimplePDF(pdfTitle: "Simple PDF Demo", authorName: "Muhammad Ishaq", 
pageSize: .A4, pageOrientation: .Portrait, 
leftMargin: 36, rightMargin: 36, topMargin: 72, bottomMargin: 36, 
textFormatter: myTextFormatter)

// now create your PDF document as usual
```
