### ISSUE TITLE
i want to add image , caption , description with 4 images in page like above in image using for loop i have array of images

### ISSUE THREAD

**Issue by zetrixweb** [ishaq/SimplePDF#18]
![466ea154-095f-11e6-872c-fc73a6a3b92c](https://cloud.githubusercontent.com/assets/15913477/14856216/d90f36b0-0cb4-11e6-82c9-ca10e6f6bbf6.png)

**Comment by ishaq** [comment]
1. add mult-column text that is supposed to be captions of the image (you can pass `NSAttributedString`s for text to control formatting)
2. add images
3. add multi-column text for description.

**Comment by ishaq** [comment]
@zetrixweb you could also do it by designing the page in a Xib file and calling `addView` to render the Xib to a PDF page.

**Comment by zetrixweb** [comment]
can i pass tableview to it direct.

**Comment by ishaq** [comment]
it should work, although i have not tried it yet.
