### ISSUE TITLE
Restrict to 4 images per page 

### ISSUE THREAD

**Issue by zetrixweb** [ishaq/SimplePDF#19]
![simulator screen shot 27-apr-2016 8 54 58 pm](https://cloud.githubusercontent.com/assets/15913477/14857569/660aa0cc-0cba-11e6-80bf-85db03365032.png)

 pdf.addImages(arrImage, imageCaptions: arrImage, imagesPerRow: 2)

**Comment by ishaq** [comment]
@zetrixweb it is not possible in the library itself. but you can call `startNewPage` after adding 4 images and then experiment with the image sizes to make sure they look right.

**Comment by ishaq** [comment]
@zetrixweb in fact, a better option is to create a Xib with the same dimensions as page, configure it the way you like it, and then pass the root view in it to `addView` function, it will render the Xib on a new page. See Readme on `addView` for more information.
