### ISSUE TITLE
Update to swift 3

### ISSUE THREAD

**Issue by XinLok007** [ishaq/SimplePDF#29]
Dear Ishaq,
your code is just awesome, great, just no words enough for it.
when i update to swift 3, there is lot of error on it.

did you update the files to swift 3?

god bless you.
Regards

**Comment by ishaq** [comment]
Hello @XinLok007,  sorry I haven't had a chance to do it yet. 

I believe upgrade would just involve running the auto-updater on it. I hope to do it sometime soon but no promises :-)

**Comment by XinLok007** [comment]
I hope too ;-)

**Comment by XinLok007** [comment]
Great man,
Thanks a lot.
