### ISSUE TITLE
Get image from document directory

### ISSUE THREAD

**Issue by ZaidSA** [ishaq/SimplePDF#36]
Hello @ishaq,

Thank you for great OpenSource.

Right now we can choose image from Main bundle as below:

`let imagePath = NSBundle.mainBundle().pathForResource("Demo", ofType: "png")!`

Is it possible we get image from document directory? Or there is something I am missing?

**Comment by ishaq** [comment]
yes, as long as you provide it with correct path, it should work.

**Comment by ZaidSA** [comment]
Thank you
