### ISSUE TITLE
Crash if CFBundleName not set

### ISSUE THREAD

**Issue by martnst** [ishaq/SimplePDF#8]
In case the `CFBundleName` is not set it crashes do to forced casting into String over [here](https://github.com/ishaq/SimplePDF/blob/master/Pod/Classes/SimplePDFUtilities.swift#L34). 
I recommend checking for `CFBundleDisplayName` alternatively.

**Comment by martnst** [comment]
Okay with some more debugging it turns out it's actually using the "wrong" infoDictionary as the localized one does not include non localized values (for some reason). Hence I think the two dicts should be merged before reading from it.

**Comment by ishaq** [comment]
good catch. let me look into this a bit more. Or if you have already found a solution, I'd love a Pull Request.

**Comment by martnst** [comment]
i guess i'll have a PR for you shortly

**Comment by ishaq** [comment]
splendid, thanks @martnst

**Comment by martnst** [comment]
@ishaq see PR #9, let me know what you think.

**Comment by ishaq** [comment]
@martnst merged, I'll release a new pod version shortly, thanks again

**Comment by martnst** [comment]
@ishaq you're welcome
